<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KawasanPoldaMetroJayaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            'BHABINKAMTIBMAS TERMINAL 1',
            'BHABINKAMTIBMAS TERMINAL 2',
            'BHABINKAMTIBMAS TERMINAL 3',
            'BHABINKAMTIBMAS KARGO',
            'BHABINKAMTIBMAS SOEWARNA',
            'BHABINKAMTIBMAS KWS JICT, PERTAMINA DIGUL KOJA ',
            'BHABINKAMTIBMAS KAWASAN PELABUHAN 1',
            'BHABINKAMTIBMAS KASAWAN PLTU DAN JLN INDUSTRI',
            'BHABINKAMTIBMAS PELABUHAN SUNDA KELAPA POLSEK KAWASAN SUNDA KELAPA',
            'BHABINKAMTIBMAS PELABUHAN MUARA ANGKE POLSEK KAWASAN SUNDA KELAPA',
            'BHABINKAMTIBMAS PELABUHAN MUARA ANGKE POLSEK KAWASAN SUNDA KELAPA',
            'BHABINKAMTIBMAS TERMINAL CAR KAWASAN KALIBARU POLSEK KAWASAN KALIBARU',
            'BHABINKAMTIBMAS KAWASAN MARUNDA',
            'BHABINKAMTIBMAS DERMAGA TIMUR KAWASAN MUARA BARU POLSEK KAWASAN MUARA BARU',
            'BHABINKAMTIBMAS PELABUHAN MUARA BARU POLSEK KAWASAN MUARA BARU',
            'BHABINKAMTIBMAS PERGUDANGAN KAWASAN MUARA BARU POLSEK KAWASAN MUARA BARU',
            'BHABINKAMTIBMAS PESISIR PANTAI BAKTI',
            'BHABINKAMTIBMAS PESISIR PAL JAYA',
            'BHABINKAMTIBMAS PESISIR TARUMAJAYA',
            'BHABINKAMTIBMAS PESISIR MARUNDA',
            'BHABINKAMTIBMAS PESISIR KALI BLENCONG',
            'BHABINKAMTIBMAS PESISIR KALI BARU',
            'BHABINKAMTIBMAS PESISIR CILINCING',
            'BHABINKAMTIBMAS PESISIR GEDUNG POMPA',
            'BHABINKAMTIBMAS PESISIR PANTAI MUTIARA',
            'BHABINKAMTIBMAS PESISIR MUARA BARU',
            'BHABINKAMTIBMAS PESISIR KALI ANGKE',
            'BHABINKAMTIBMAS PESISIR KALI ADEM',
            'BHABINKAMTIBMAS PESISIR KALI KRESEK',
            'BHABINKAMTIBMAS PESISIR KALI CBL'
        ];

        foreach ($data as $kawasan) {
            DB::table('kawasan')->insert(['province_code' => 31, 'name' => $kawasan]);
        }
    }
}
